Module2 task1
htmlacademy-yii/1261731-task-force-1 pull request #6
Opened 2020-03-21 15:31 UTC by igor193php

2021-03-09 06:41 UTC, lwdmk requested changes

2021-03-09 06:41 UTC, lwdmk commented on schema.sql
> +    specialization_id   INT   UNSIGNED NOT NULL,
по текущей логике один пользователь будет иметь только одну специализацию, это не совсем так, лучше многие-ко-многим связь сделать через промежуточную таблицу

2021-03-09 06:41 UTC, lwdmk commented on schema.sql
> +    show_profile        BIT,
обычно для флагов используют либо tinyint(1) для у нас mysql (хотя в новых версиях вроде они ввели таки  boolean), либо boolean если у нас постресс, лучше придерживаться общепринятых практик, хотя бы для того, чтобы не иметь проблем с приведением типов в будущем

2021-03-09 06:41 UTC, lwdmk commented on schema.sql
> +    notefecation        BIT,
1. notification
2. название поле не отражает суть, если это показатель включены ли уведомления, то лучше использовать что-то более говорящее например is_notification_enabled, лучше пусть будет длинное название, но зато будет понятно зачем оно

2021-03-09 06:41 UTC, lwdmk commented on schema.sql
> +CREATE TABLE locations (
locations это что-то связанное с координатами обычно, в нашем случае речь вроде про города идет

2021-03-09 06:41 UTC, lwdmk commented on schema.sql
> +    name              CHAR (50)       NOT NULL,
для обозначение строковых полей используют varchar.
под char  выделяется фиксированный объем памяти, не зависимо от того, какой реальный объем хранится в поле. под varchar происходит динамическое выделение в зависимости от информации что в этом поле хранится. Задается лишь потолок. соотвественно varchar  позволяет оптимизировать занимаемое место таблицами

2021-03-09 06:41 UTC, lwdmk commented on schema.sql
> +    name              CHAR (50),
я бы завязывался на том, что название города будет уникальным. Можно лишь утверждать что оно может быть уникальным в пределах региона. Тогда нужна еще таблица региона, а ключ уникальности будет region_id, name.

Итого либо нужно убрать уникальность поля, либо ввести таблицу регионов (в любом случае к этому придется придти)

2021-03-09 06:41 UTC, lwdmk commented on schema.sql
> +    path_file         CHAR (255),
файль вложение всегда будет 1?

2021-03-09 06:41 UTC, lwdmk commented on schema.sql
> +    repayment         DECIMAL (12, 2),
по-помоему лучше использовать более говорящее название, например budget

2021-03-09 06:41 UTC, lwdmk commented on schema.sql
> +    description       TEXT           NOT NULL,
лучше путь description будет nullable

2021-03-09 06:41 UTC, lwdmk commented on schema.sql
> +CREATE TABLE responses (
у слова responses  несколько другой оттенок значения, лучше подойдет replies

2021-03-09 06:41 UTC, lwdmk commented on schema.sql
> +    rating             INT   UNSIGNED,
мне кажется тут речь скорее всего про отзывы review, а не про комментарии.
у отзыва должен быть автор, а не только человек, на которого отзыв оставлен.

2021-03-09 06:41 UTC, lwdmk commented on schema.sql
> +    executor            BIT,
какого назначение этого поля?

2021-03-09 06:41 UTC, lwdmk commented on schema.sql
> +                        FOREIGN KEY (location_id)        REFERENCES locations (id)
согласно техническому заданию у пользователя должен быть раздел Фото работ, где он будет храниться?

2021-03-09 06:41 UTC, lwdmk commented on schema.sql
> +CREATE TABLE users (
> Верхняя часть основного контента страницы предназначается для краткой характеристики юзера: его имя, аватар, город, возраст и рейтинг.

у нас негде хранить аватар и возраст

2021-03-09 06:41 UTC, lwdmk commented on schema.sql
> +CREATE TABLE users (
Негде хранить дату последней активности пользователя,

2021-03-09 06:41 UTC, lwdmk commented on schema.sql
> +                       UNIQUE (name)
а зачем отдельная таблица для статусов и что такое symbol_code?
обычно отдельная таблица нужна, когда используются вручную добавляемые статусы, насколько знаю это не наш кейс

2021-03-09 06:41 UTC, lwdmk commented on schema.sql
> +    id                INT   UNSIGNED NOT NULL AUTO_INCREMENT,
согдасно ТЗ

> Локация
> 
> При выборе локации пользователь вводит город/район/улицу, а геокодер на стороне клиента подставляет значения (широта, долгота, название города) в скрытые поля формы. На стороне PHP необходимо убедиться, что широта и долгота являются корректными координатами, а название города присутствует в таблице городов.

нам нужно хранить координаты локации задания

2021-03-09 06:41 UTC, lwdmk commented on schema.sql
> +);
в текущей схеме нет места для хранения текущего исполнителя для задания

2021-03-09 06:41 UTC, lwdmk commented on schema.sql
> +    user_id           INT   UNSIGNED  NOT NULL,
чаты обычно между 2 пользователями в рамках задания, не хватает поля для еще одного пользователя

2021-03-09 06:42 UTC, lwdmk commented
+ по всем таблицам (кроме промежуточных для связи многие-ко-многим) нужны поля created_at, updated_at

2021-03-14 16:03 UTC, igor193php commented on schema.sql
> +    name              CHAR (50)       NOT NULL,
Готово

2021-03-14 16:03 UTC, igor193php commented on schema.sql
> +CREATE TABLE locations (
Готово

2021-03-14 16:03 UTC, igor193php commented on schema.sql
> +    notefecation        BIT,
Готово

2021-03-14 16:03 UTC, igor193php commented on schema.sql
> +    show_profile        BIT,
Готово

2021-03-14 16:03 UTC, igor193php commented on schema.sql
> +    specialization_id   INT   UNSIGNED NOT NULL,
Готово

2021-03-14 17:09 UTC, igor193php commented on schema.sql
> +);
Готово

2021-03-14 19:12 UTC, igor193php commented on schema.sql
> +    id                INT   UNSIGNED NOT NULL AUTO_INCREMENT,
Готово

2021-03-14 19:14 UTC, igor193php commented on schema.sql
> +                       UNIQUE (name)
Готово

2021-03-14 19:25 UTC, igor193php commented on schema.sql
> +CREATE TABLE users (
Готово

2021-03-14 20:05 UTC, igor193php commented on schema.sql
> +    user_id           INT   UNSIGNED  NOT NULL,
Готово

2021-03-14 20:15 UTC, igor193php commented on schema.sql
> +    path_file         CHAR (255),
Готово

2021-03-14 20:22 UTC, igor193php commented on schema.sql
> +    repayment         DECIMAL (12, 2),
Готово

2021-03-14 20:27 UTC, igor193php commented on schema.sql
> +CREATE TABLE responses (
Готово

2021-03-14 20:33 UTC, igor193php commented on schema.sql
> +    rating             INT   UNSIGNED,
Готово

2021-03-14 20:38 UTC, igor193php commented on schema.sql
> +    executor            BIT,
Поле executor удалил

2021-03-14 20:44 UTC, igor193php commented on schema.sql
> +                        FOREIGN KEY (location_id)        REFERENCES locations (id)
Готово

2021-03-16 07:01 UTC, lwdmk approved these changes

2021-03-16 07:01 UTC, merged