Исключительный тип
htmlacademy-yii/1261731-task-force-1 pull request #8
Opened 2021-08-26 16:44 UTC by igor193php

---
:mortar_board: [Исключительный тип](https://up.htmlacademy.ru/yii/1/user/1261731/tasks/7)

2021-08-30 09:54 UTC, nikserg requested changes

2021-08-30 19:24 UTC, igor193php commented on src/CancelAction.php
> +    public function validateAccessUser(int $idCurrentUser, int $idCustomer, int $idExecute) { bool
исправлено

2021-08-31 12:38 UTC, nikserg requested changes

2021-08-31 12:38 UTC, nikserg commented on tests/TaskTest.php
> +    error_log($e-getMessage());
Не исправлено. Для удобства отмечай комментарии, по которым ты внес правки. Ставь плюсик, или пиши "исправлено".

2021-08-31 12:58 UTC, igor193php commented on tests/TaskTest.php
> +    error_log($e-getMessage());
+

2021-08-31 13:26 UTC, merged